sudo: required
dist: trusty

language: c

services:
  - docker

before_install:
  - pip install --user --upgrade awscli
  - git fetch --tags --unshallow

matrix:
  include:
    - env:
        - TRAVIS_TARGET=docker-make-image
      script:
        - make firmware
        - make docker-setup
        - bash -c "while true; do sleep 1m; echo ...; done" &
        - set -o pipefail && make docker-make-image 2>&1 | tee -a build.out | grep --line-buffered '^>>>'
      after_success:
        - PRODUCT_VERSION=v3 PRODUCT_REV=prod ./publish.sh build.out buildroot/output/images/piksiv3_prod/*
        - SLACK_CHANNEL=github ./comment.sh
      after_failure:
        - tail -n 500 build.out

    - env:
        - TRAVIS_TARGET=docker-make-host-image
      script:
        - make firmware
        - make docker-setup
        - bash -c "while true; do sleep 1m; echo ...; done" &
        - set -o pipefail && make docker-make-host-image 2>&1 | tee -a host_build.out | grep --line-buffered '^>>>'
      after_success:
        - git fetch --tags --unshallow
        - PRODUCT_VERSION=v3 PRODUCT_REV=prod ./publish.sh host_build.out
      after_failure:
        - tail -n 500 host_build.out

env:
  global:
    # Secure keys below are encrypted with travis encrypt gem
    # Example encryption: travis encrypt AWS_SECRET_ACCESS_KEY=foo
    # See https://docs.travis-ci.com/user/encryption-keys/
    # AWS_ACCESS_KEY_ID
    - secure: Ls9hEi04qvyDOEBbmDeNCjP7yfrQdke0EMFB8289xZPDrYNnysJmKzyh4Pt9PUyT7Y9pzrI1HKSziisshfQZWhhvG6K1fnM5glChoesK2pg4zeoz44gCsU/zGJqBNBH8z6VQgmAzeHvBPvOO9UJMy7ywD2Wz9+nQsYbWLgVE/63YuzEFsHI3jqLz5EyM4umpq2i6joQcD3Pdlvgs8KZj56lQ2IxrkTf1QMlwFN2/xmKa0eQctonCP7MwVyVCZEILUgpk7e0glfn86A+53fej/S8UhmCH6XHwUw9FQrmtEl4pwPmU1bna1pncWIorGChhcPorWD0ePfOCT4AKIrQAveaiSN/tnCzcmccVnGpe8WWXoRwFQ6B8110PbSwZlB9H5UUmZcpwmvIXnPyedbGVSXT2p2ubsjGBWbtnFj/uAms4izGAmOLUrvOx+rCb4ol2rP4WEnW22U927y6sotSAuj1BOkt4/x4nP6CZQNDXIOS4+kLRDjtNUrMFENhxbsdXbQ5ANZO5ssDPwI3hqNYamQWYKyasXgueLMBQdfaQ32nxBMQmN8dbvThsT/klQmsp5YoihndK6SGuF2IEIuWZG0cWACGnjHzrcv4dfBO2V5/7aoVhmSMKTUAvxkZsITYZuorUe+2HwQl6n59+0A2FhQdRLDMAXrOK7AN2faoJFhw=
    # AWS_SECRET_ACCESS_KEY
    - secure: vNHhGAZoaGmTiZ/Bjf0pqx4w9T37sDJNUOp6C5EXCapXAsYx+4G8v3xNlWBHWrPAs5q4XHJgbcNH7k1tRAI3nwd0RCv14SBNsVv5eouzpPd+o2ploDGCW++p/CL1kjQJBOqmz9sYCwxqra9LG7MCA/MzTG3eNa4/3lCf2tut7yhtxHbhIrVBaFgiHPYoZ1Pe6DPTQjjp32Xf2UHElHfa3oDQ/pw45hKWdwBx+fQjfLl1fVbHE3AhuXd7Q51tmL3qPNVox4/oLkmwpggzF0LoDQDZbZmOFSzcIiv/cpnqkaP9iy3TVQelrZivN9EXiyZsyhcrXll2pll/hvbg+cPVxBnC+p+yrPyZ4CaNwgID3c8ZRiPjJoyo+z4wxse3AaMv2AGsHVNGavYm61nFcJsRc0FQUfvkksdDu3LdfQbxkAKK7vgM7k4jWlcHe8wmQOXf/EPl5Hd2RNwHDfSEfR8YGPBDqsrdDFRO1fi/+kwpkLTfgN7WqbBBHCax54gQ1GZAEJC3nPqqnajKU/oduA4lXB2VJXlFl/NMeoX/z508Kc9wxaATCUFhGB68H2kKx8WT1ZMuBo9Eu7nXYSXg9jA+kCcb7GW3QgWk9h1Klcf6v5vw59UCFCEGfnPYinnWp6LMPHIY8q7ChpfEYq6rDma7o4bYExUHGo9Qip/qeEypetI=
    # GITHUB_TOKEN
    - secure: "x8K9GXfhLM+uVxsD4BB9MowOXxowzx/PUAccQpXWLjoQi4GnIFPGNASkFJNL7EVo4IwX7fiG6FE14SfG+jybYB5t5R9BUis5wKSO1ghUUO4SOLHBNW04YfwVn9p33YuipOL/N+Co74jSh0oEDacaN1TTLP6RuFyrLy0ew8JwE+EiRpNc2NMLSIap0C0ePkrtultvx9NnZ0aTJ1mhs2lOesqBPSvWXlglQqPcseldBcpTt1ch+m9I41xxzQzmOnGyka59wvqLyJDaJEzKI0kJobwwZY6OOANz3Yvrus1ahAhGXsRwjuJWdyrkV5uXuWE2KLy1MY31fFqh6I/9FMdvEBt2zCtkMLtOYjn7IpiOom0P0cZkGXJeGlTMojaw1eostC5mZCYKf6gNtGOc95U9r3hDSHhYFeLCj5rE14SGjh84uogx6rO8vGYbjl3vgpdVFJy37Xx7tQHyueLfrUVATjuGc4/x7Ukez4Vb9thfXcHvV1W77YfEIM0uM2HSpFOdWq7lbNDcLSAkmJHdEZcssDoaUhCqFz8YFeSyEW4iZF6j5Uqljkkuj1YDIcrkF5ggbmoZGfZL85iDedVsYPdxgXTBiXEcJGfbTfD7X36Uc6+6jxpVUZDgF5dBF6jCK9gdVLgiGLU0NcSCTork1lNByuKNmsp34GLTJso9OAiHsTI="
    # SLACK_TOKEN
    - secure: "g0KII9TK5MhOS3j9h68jzQZk1bn6mVIaSMPrtB9aA7jrEMALm6biP+pYL2CgWyzGtFbsFVIG81fuyMpYjMR3ImFI/sGh+w0650HMaD97TEWYVc/gVtqjZsDbzGYtmG9tmxahJxl/LjAsO2xmddVYKlpyVzCGtAECe0IWX7LxYODIr01NQgmh6X+DClb1S6P1S6jgO4tjsnatstYo3us4jGHLqSDz9n9pH70YzZn8EB2cDQkLA5visc/w3mAMqmA3a3RWoBMNd3M63zEdlHWtiEaPY9JYDGASP1gp4rXAwKk5RTnNw6BBhVqqInfs1gFpXVve5zNus/YUZ342NuCyy2+pSSmJyWmA26pKE+PtHOoMuUwCqCrC/OdoLX7p7PTO++4XIr2vYV7KPlFELfzvlnCjXqlq8+AaiSb6z4FGijuHXRWNVvnasTcP3MDJn5OtjtBBNTiYm9fYj+z6PNVf9DwZbukiHN3GKNFEBGA1ACMvkD12BjDfrHsgLqHPUd9oRhU1qNGQVZozmVeKRczsP2lhwQp1GdrLhaz1ABeT0IjYqm+87LuE5eR0oQ/5ETOCDHdlfd4Vf6oz68lvkBbb2Yof55eJrSPUIzmLqCucEC1TI9WZui7isyRkhH9K5XCMQS0FKx6AvATOP4aG6zy8N5jAUYupR+NsCbDJUsQRc54="
