sudo: required

language: c

services:
  - docker

before_install:
  - pip install --user --upgrade awscli

install:
  - ./fetch_firmware.sh

script:
  - travis_wait 60 docker build -t piksi-buildroot .

after_success:
  - mkdir -p buildroot/output
  - export CONTAINER=`docker create piksi-buildroot`
  - docker cp $CONTAINER:/app/buildroot/output/images buildroot/output
  - git fetch --tags --unshallow
  - PRODUCT_VERSION=v3 PRODUCT_REV=prod ./publish.sh buildroot/output/images/piksiv3_prod/*
  - SLACK_CHANNEL=github ./comment.sh

env:
  global:
    # Secure keys below are encrypted with travis encrypt gem
    # Example encryption: travis encrypt AWS_SECRET_ACCESS_KEY=foo
    # See https://docs.travis-ci.com/user/encryption-keys/
    # AWS_ACCESS_KEY_ID
    - secure: Ls9hEi04qvyDOEBbmDeNCjP7yfrQdke0EMFB8289xZPDrYNnysJmKzyh4Pt9PUyT7Y9pzrI1HKSziisshfQZWhhvG6K1fnM5glChoesK2pg4zeoz44gCsU/zGJqBNBH8z6VQgmAzeHvBPvOO9UJMy7ywD2Wz9+nQsYbWLgVE/63YuzEFsHI3jqLz5EyM4umpq2i6joQcD3Pdlvgs8KZj56lQ2IxrkTf1QMlwFN2/xmKa0eQctonCP7MwVyVCZEILUgpk7e0glfn86A+53fej/S8UhmCH6XHwUw9FQrmtEl4pwPmU1bna1pncWIorGChhcPorWD0ePfOCT4AKIrQAveaiSN/tnCzcmccVnGpe8WWXoRwFQ6B8110PbSwZlB9H5UUmZcpwmvIXnPyedbGVSXT2p2ubsjGBWbtnFj/uAms4izGAmOLUrvOx+rCb4ol2rP4WEnW22U927y6sotSAuj1BOkt4/x4nP6CZQNDXIOS4+kLRDjtNUrMFENhxbsdXbQ5ANZO5ssDPwI3hqNYamQWYKyasXgueLMBQdfaQ32nxBMQmN8dbvThsT/klQmsp5YoihndK6SGuF2IEIuWZG0cWACGnjHzrcv4dfBO2V5/7aoVhmSMKTUAvxkZsITYZuorUe+2HwQl6n59+0A2FhQdRLDMAXrOK7AN2faoJFhw=
    # AWS_SECRET_ACCESS_KEY
    - secure: vNHhGAZoaGmTiZ/Bjf0pqx4w9T37sDJNUOp6C5EXCapXAsYx+4G8v3xNlWBHWrPAs5q4XHJgbcNH7k1tRAI3nwd0RCv14SBNsVv5eouzpPd+o2ploDGCW++p/CL1kjQJBOqmz9sYCwxqra9LG7MCA/MzTG3eNa4/3lCf2tut7yhtxHbhIrVBaFgiHPYoZ1Pe6DPTQjjp32Xf2UHElHfa3oDQ/pw45hKWdwBx+fQjfLl1fVbHE3AhuXd7Q51tmL3qPNVox4/oLkmwpggzF0LoDQDZbZmOFSzcIiv/cpnqkaP9iy3TVQelrZivN9EXiyZsyhcrXll2pll/hvbg+cPVxBnC+p+yrPyZ4CaNwgID3c8ZRiPjJoyo+z4wxse3AaMv2AGsHVNGavYm61nFcJsRc0FQUfvkksdDu3LdfQbxkAKK7vgM7k4jWlcHe8wmQOXf/EPl5Hd2RNwHDfSEfR8YGPBDqsrdDFRO1fi/+kwpkLTfgN7WqbBBHCax54gQ1GZAEJC3nPqqnajKU/oduA4lXB2VJXlFl/NMeoX/z508Kc9wxaATCUFhGB68H2kKx8WT1ZMuBo9Eu7nXYSXg9jA+kCcb7GW3QgWk9h1Klcf6v5vw59UCFCEGfnPYinnWp6LMPHIY8q7ChpfEYq6rDma7o4bYExUHGo9Qip/qeEypetI=
    # GITHUB_TOKEN
    - secure: "vcYhHIgWQNsEwx/e9zXuLn3Sc8AjZuYZ/X3mjUiEEHZapfAEldaFKqdiSAFP8pPG1Ht/mxxX6QrBrelbIBgjZ5V1Jp/Sq6aiN5rBX9tUc64hOv8016MoxfxopzkrQ9U8dzJVnYlkemmJ8eMibLpnjfCtSX4bLkh8AEj3fmy/LeHvk+SCNCBhbULXJolLZV5+7OLbiS10ZIC0S37RxBkRHx1RzuNqsk8nVyyIrYGq33dc7WdLgVZLPBqApKB/2p474psMxnOYkLmbrzPVfszXn+6OR243Y7EqwbppdjIJ4CzuIfxwmtlRNosKHzXf6KvDu1r9sWLpp48Z+OWKn/+59FDMiYnmMPH05MQEg4M9zeoGhJoHVF+f6twAmJVCRO3+u8N/mcCW2DwfAZI6Rebj1OPRnn6YlNsc4VjJO+SKJP0v8Jqx2xFbwpE4T+LCXBksbNLH10K9eNnvFwwyyG1eBwPaEnzpuX5f3d8LT4TSEc5L38dc5ctMIIodFXqQDEBimo8S617BPS+gvt83vsRwWqUNTpriEoZ1UUsMfDz3eE8AGTufqHW6d35GTvfpXCl9tzpxElTWladZIqT+/q6/zD9i0bVwzVvbbsey9tnnW0Js12OT0qOkdgpM3ScjL+PEhtUhZfvgpge2TGPpXOhPn7ZQPkWa727vwxzuutCgmR0="
    # SLACK_TOKEN
    - secure: "g0KII9TK5MhOS3j9h68jzQZk1bn6mVIaSMPrtB9aA7jrEMALm6biP+pYL2CgWyzGtFbsFVIG81fuyMpYjMR3ImFI/sGh+w0650HMaD97TEWYVc/gVtqjZsDbzGYtmG9tmxahJxl/LjAsO2xmddVYKlpyVzCGtAECe0IWX7LxYODIr01NQgmh6X+DClb1S6P1S6jgO4tjsnatstYo3us4jGHLqSDz9n9pH70YzZn8EB2cDQkLA5visc/w3mAMqmA3a3RWoBMNd3M63zEdlHWtiEaPY9JYDGASP1gp4rXAwKk5RTnNw6BBhVqqInfs1gFpXVve5zNus/YUZ342NuCyy2+pSSmJyWmA26pKE+PtHOoMuUwCqCrC/OdoLX7p7PTO++4XIr2vYV7KPlFELfzvlnCjXqlq8+AaiSb6z4FGijuHXRWNVvnasTcP3MDJn5OtjtBBNTiYm9fYj+z6PNVf9DwZbukiHN3GKNFEBGA1ACMvkD12BjDfrHsgLqHPUd9oRhU1qNGQVZozmVeKRczsP2lhwQp1GdrLhaz1ABeT0IjYqm+87LuE5eR0oQ/5ETOCDHdlfd4Vf6oz68lvkBbb2Yof55eJrSPUIzmLqCucEC1TI9WZui7isyRkhH9K5XCMQS0FKx6AvATOP4aG6zy8N5jAUYupR+NsCbDJUsQRc54="
