[package]
name = "ota_tool"
version = "0.1.0"
authors = ["Swift Navigation <dev@swiftnav.com>"]

[dependencies]
reqwest = "0.8.5"
hyper = "0.11.24"
uuid = "0.6.2"
serde = "1.0.36"
serde_derive = "1.0.36"
serde_json = "1.0.13"
clap = "2.31.2"

[profile.release]
lto = true

